### ISSUE TITLE
After update to ESPHOME  2021.11.1 install error: fatal error: SPI.h: No such file or directory

### ISSUE THREAD

**Issue by ervu** [Scriptman/ESPHome_ITHO_Eco_Fan_CC1101#13]
Thank you so much for making this available. 

After updating to ESPHOME version 2021.11.1 the install action shows an error that the SPI.h is not found.
Can you give a tip on what could be the cause of this issue?

Thanks !

I am using HASSIO running as a VM
core-2021.11.5
supervisor-2021.10.8
Current version: 2021.11.1

------------------------------------------------------------------------------------------------------------------------------------

Compiling /data/iot-itho/.pioenvs/iot-itho/src/main.cpp.o
Compiling /data/iot-itho/.pioenvs/iot-itho/lib634/ESPHome_ITHO_Eco_Fan_CC1101/CC1101.cpp.o
In file included from /data/iot-itho/.piolibdeps/iot-itho/ESPHome_ITHO_Eco_Fan_CC1101/IthoCC1101.h:9:0,
                 from src/CC1101.h:2,
                 from src/main.cpp:51:
/data/iot-itho/.piolibdeps/iot-itho/ESPHome_ITHO_Eco_Fan_CC1101/CC1101.h:10:17: fatal error: SPI.h: No such file or directory

*************************************************************
* Looking for SPI.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:SPI.h"
* Web  > https://platformio.org/lib/search?query=header:SPI.h
*
*************************************************************

 #include <SPI.h>
                 ^
compilation terminated.
*** [/data/iot-itho/.pioenvs/iot-itho/src/main.cpp.o] Error 1
In file included from /data/iot-itho/.piolibdeps/iot-itho/ESPHome_ITHO_Eco_Fan_CC1101/CC1101.cpp:5:0:
/data/iot-itho/.piolibdeps/iot-itho/ESPHome_ITHO_Eco_Fan_CC1101/CC1101.h:10:17: fatal error: SPI.h: No such file or directory

**Comment by Haringstad** [comment]
Same issue here.

**Comment by Scriptman** [comment]
I was running 2021.10.3, but having the same issue with 2021.11.1

Working on a fix

**Comment by Scriptman** [comment]
Fixed.

Please add these libraries to the esphome yaml config:

    - SPI
    - Ticker

**Comment by ervu** [comment]
Hi, i have change my project yaml file, but still have the same issue. Do  I miss something?

esphome:

  includes: 
    - common/CC1101.h
  libraries: 
    - https://github.com/Scriptman/ESPHome_ITHO_Eco_Fan_CC1101.git
    - SPI
    - Ticker

**Comment by Scriptman** [comment]
Can you add the 2 libraries before the github link? I have:- SPI- Tracker- https://github.....Maybe the order of the libraries are important, not sure thoughOp 24 nov. 2021 15:53 schreef Erik ***@***.***>:
Hi, i have change my project yaml file, but still have the same issue. Do  I miss something?
esphome:
includes:
- common/CC1101.h
libraries:
- https://github.com/Scriptman/ESPHome_ITHO_Eco_Fan_CC1101.git
- SPI
- Ticker

**Comment by Haringstad** [comment]
Yeppers! Fixed it for me too! Thank you again!
Regards,

Jacco van Koll
